/* REGISTRO_EVENTOS */
-- 1 Registro
INSERT INTO REGISTRO_EVENTOS (ID_REG_EVE, NOM_REG_EVE, APE_REG_EVE, COR_REG_EVE, CEL_REG_EVE, PRO_REG_EVE, LDP_REG_EVE)
VALUES ('24856' , 'FERNANDO ROBERTO' , 'QUISPE CARRION' , 'yemeg76034@keshitv.com', '858553060', 'Profesor', 'Imperial');
-- 2 Registro
INSERT INTO REGISTRO_EVENTOS (ID_REG_EVE, NOM_REG_EVE, APE_REG_EVE, COR_REG_EVE, CEL_REG_EVE, PRO_REG_EVE, LDP_REG_EVE)
VALUES ('43760' , 'KEVIN ANGEL' , 'GONZALES DIAZ' , 'kouralleyaudau-6222@yopmail.com', '858553060', 'Director', 'Cerro Azul');
-- 3 Registro
INSERT INTO REGISTRO_EVENTOS (ID_REG_EVE, NOM_REG_EVE, APE_REG_EVE, COR_REG_EVE, CEL_REG_EVE, PRO_REG_EVE, LDP_REG_EVE)
VALUES ('84960' , 'BRYAN ALVA' , 'RODRIGUEZ GONZALES' , 'crirerivoicrou-8752@yopmail.com', '858553060', 'Ingeniero', 'Quilmana');
-- 4 Registro
INSERT INTO REGISTRO_EVENTOS (ID_REG_EVE, NOM_REG_EVE, APE_REG_EVE, COR_REG_EVE, CEL_REG_EVE, PRO_REG_EVE, LDP_REG_EVE)
VALUES ('35621' , 'JAVIER FRANCIS' , 'FERNANDEZ RODRIGUEZ' , 'hehaucaveusa-7188@yopmail.com', '858553060', 'Doctor', 'Cerro Alegre');
-- 5 Registro
INSERT INTO REGISTRO_EVENTOS (ID_REG_EVE, NOM_REG_EVE, APE_REG_EVE, COR_REG_EVE, CEL_REG_EVE, PRO_REG_EVE, LDP_REG_EVE)
VALUES ('12458' , 'ALEX ALEJO' , 'DIAZ LOPEZ' , 'raddeleixograu-6253@yopmail.com', '858553060', 'Odontologo', 'Pacaran');
-- 6 Registro
INSERT INTO REGISTRO_EVENTOS (ID_REG_EVE, NOM_REG_EVE, APE_REG_EVE, COR_REG_EVE, CEL_REG_EVE, PRO_REG_EVE, LDP_REG_EVE)
VALUES ('74851' , 'RONY PEPE' , 'ROMERO FLORES' , 'preusougaruppeu-5616@yopmail.com', '858553060', 'Albañil', 'Nuevo Imperial');
-- 7 Registro
INSERT INTO REGISTRO_EVENTOS (ID_REG_EVE, NOM_REG_EVE, APE_REG_EVE, COR_REG_EVE, CEL_REG_EVE, PRO_REG_EVE, LDP_REG_EVE)
VALUES ('42845' , 'JESUS ALEX' , 'CRUZ SANCHEZ' , 'reppugracozau-4458@yopmail.com', '858553060', 'Arquitecto', 'San Vicente');
-- 8 Registro
INSERT INTO REGISTRO_EVENTOS (ID_REG_EVE, NOM_REG_EVE, APE_REG_EVE, COR_REG_EVE, CEL_REG_EVE, PRO_REG_EVE, LDP_REG_EVE)
VALUES ('75629' , 'JIMENA' , 'GOMEZ PEREZ' , 'fiyufeunneitri-7116@yopmail.com', '858553060', 'Dentista', 'San Luis');
-- 9 Registro
INSERT INTO REGISTRO_EVENTOS (ID_REG_EVE, NOM_REG_EVE, APE_REG_EVE, COR_REG_EVE, CEL_REG_EVE, PRO_REG_EVE, LDP_REG_EVE)
VALUES ('13485' , 'SILVESTER FERNAN' , 'MARTINEZ RUIZ' , 'zequacautexi-1453@yopmail.com', '858553060', 'Arqueologo', 'Quilmana');
-- 10 Registro
INSERT INTO REGISTRO_EVENTOS (ID_REG_EVE, NOM_REG_EVE, APE_REG_EVE, COR_REG_EVE, CEL_REG_EVE, PRO_REG_EVE, LDP_REG_EVE)
VALUES ('45251' , 'DIEGO TOSHI' , 'QUIROGA ROODRIGUES' , 'pauteumeureppe-2927@yopmail.com', '858553060', 'Escritor', 'Zuñiga');

SELECT * FROM REGISTRO_EVENTOS